name: WildTools
version: 2.6.0
api-version: 1.13
main: com.bgsoftware.wildtools.WildToolsPlugin
description: Configurable trench picks, tray picks, sell-wands, harvester-hoes and more!
website: http://wildseries.xyz/
authors: [Ome_R, WildSeries]
softdepend: [NoCheatPlus, Spartan, AAC, mcMMO, Vault, ShopGUIPlus, Essentials, Factions]
commands:
  tools:
    description: List of all wildtools command
permissions:
  wildtools.*:
    description: Gives access to all the command.
    default: op
    children:
      wildtools.use: true
      wildtools.give: true
      wildtools.info: true
      wildtools.reload: true
      wildtools.sellmode: true
      wildtools.settings: true
  wildtools.use:
    description: Gives access to use the custom tools.
    default: true
  wildtools.give:
    description: Gives access to give tools to other players.
  wildtools.info:
    description: Gives access to get information about tools.
  wildtools.reload:
    description: Gives access to reload all configuration files.
  wildtools.sellmode:
    description: Gives access to use harvester sell mode.
  wildtools.settings:
    description: Gives access to use settings editor.