package xyz.wildseries.wildtools.config;

@SuppressWarnings("unused")
public final class ConfigComments {

    @Comment("####################################################")
    @Comment("##                                                ##")
    @Comment("##            WildTools Configuration             ##")
    @Comment("##               Developed by Ome_R               ##")
    @Comment("##                                                ##")
    @Comment("####################################################")
    public static String HEADER = "";

    @Comment("")
    @Comment("Choose which prices plugin to check for prices (ShopGUIPlus, Essentials, WildTools).")
    public static String PRICES_PLUGIN = "prices-plugin";

    @Comment("")
    @Comment("A list of prices. Use \"TYPE\" and \"TYPE:DATA\" formats.")
    public static String PRICES_LIST = "prices-list";

    @Comment("")
    @Comment("")
    @Comment("The plugin brings a lot of options and features for making tools easily with rich-configuration options.")
    @Comment("The default config has basic trench-pickaxe, tray-pickaxe, sand-wand, sell-wand, lightning-wand, harvester-hoe")
    @Comment("and cannon-wand examples. Each tool-mode has it's own configuration options, make sure you don't mix them.")
    @Comment(" ")
    @Comment("*** Builder Tool-Mode ***")
    @Comment("Tools in this mode will create a pillar of the same block as the clicked one.")
    @Comment("Required sections:")
    @Comment("length: The length of the pillar (INTEGER)")
    @Comment(" ")
    @Comment("*** Cuboid Tool-Mode ***")
    @Comment("Tools in this mode will dig a cuboid-area (for example, 3x3x3). This mode is used for trench and tray pickaxes.")
    @Comment("Required sections:")
    @Comment("break-level: How big the cuboid-area gonna be (3 will be 3x3x3 area) [INTEGER]")
    @Comment(" ")
    @Comment("*** Drain Tool-Mode ***")
    @Comment("Tools in this mode will remove all ice blocks in the checking area.")
    @Comment("Required sections:")
    @Comment("radius: What is the radius of the checking area? (3 will check a 7x7 area) (INTEGER)")
    @Comment(" ")
    @Comment("*** Pillar Tool-Mode ***")
    @Comment("Tools in this mode will dig a pillar of blocks with the same type. This mode is used for sand-wands.")
    @Comment(" ")
    @Comment("*** Sell Tool-Mode ***")
    @Comment("Tools in this mode will sell all the container's contents. This mode is used for sell-wands.")
    @Comment(" ")
    @Comment("*** Lightning Tool-Mode ***")
    @Comment("Tools in this mode will strike a lightning to charge creepers. This mode is used for lightning-wands.")
    @Comment(" ")
    @Comment("*** Harvester Tool-Mode ***")
    @Comment("Tools in this mode will harvest seeds and replant them automatically. This mode is used for harvester-hoes.")
    @Comment("Drops support silk-touch and fortune.")
    @Comment("Required sections:")
    @Comment("radius: What is the radius of the checking area? (3 will check a 7x7 area) (INTEGER)")
    @Comment("Optional sections:")
    @Comment("farmland-radius: What is the radius of the checking for dirt area? (Same as radius)")
    @Comment("active-action: Which action should activate the harvester? (RIGHT_CLICK or LEFT_CLICK)")
    @Comment(" ")
    @Comment("*** Ice Tool-Mode ***")
    @Comment("Tools in this mode will smelt all ice blocks in the checking area.")
    @Comment("Required sections:")
    @Comment("radius: What is the radius of the checking area? (3 will check a 7x7 area) (INTEGER)")
    @Comment(" ")
    @Comment("*** Cannon Tool-Mode ***")
    @Comment("Tools in this mode will fill all dispensers in a selected area with tnt. This mode is used for cannon-wands.")
    @Comment("Right-click and left-click to select an area.")
    @Comment("Required sections:")
    @Comment("tnt-amount: How many tnt will be filled in each dispenser? (INTEGER)")
    @Comment(" ")
    @Comment("*** Crafting Tool-Mode ***")
    @Comment("Tools in this mode will auto-craft items in a container.")
    @Comment("Required sections:")
    @Comment("craftings: All the crafting *results* for the tool (LIST)")
    @Comment("     Please follow the \"TYPE\" or \"TYPE:DATA\" format for results.")
    @Comment(" ")
    @Comment("*** Sell Tool-Mode ***")
    @Comment("Tools in this mode will sell all the clicked chest's contents.")
    @Comment(" ")
    @Comment("*** Sort Tool-Mode ***")
    @Comment("Tools in this mode will sort all the clicked chest's contents.")
    @Comment(" ")
    @Comment("There are sections that can be applied for all the tools:")
    @Comment("cooldown: Cool-down between uses in milliseconds (INTEGER) (Default 0)")
    @Comment("auto-collect: Drops will go straight into the inventory (BOOLEAN) (Default false)")
    @Comment("silk-touch: Tool will have a hidden silk-touch enchantment (BOOLEAN) (Default false)")
    @Comment("only-same-type: Only blocks with the same type will be dug. (BOOLEAN) (Default false)")
    @Comment("only-inside-claim: Will only work on blocks inside claim land.")
    @Comment("unbreakable: Tool will never be broken (BOOLEAN) (Default false)")
    @Comment("uses: Custom durability for the tool (INTEGER)")
    @Comment("     If both unbreakable and uses are not set, tool will use the vanilla durability (supports unbreaking enchantment)")
    @Comment("keep-inventory: Tool won't get dropped from players inventory (BOOLEAN) (Default false)")
    @Comment("type: Material type (Check https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)")
    @Comment("name: Custom name for the tool (STRING)")
    @Comment("lore: Custom lore for the tool (LIST)")
    @Comment("glow: Glow effect for the tool (BOOLEAN)")
    @Comment("enchants: Enchantments for the tool (LIST)")
    @Comment("     Please follow the \"ENCHANTMENT:LEVEL\" format for enchantments.")
    @Comment("     (Check https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html)")
    @Comment("whitelisted-blocks: Which blocks will be dug by the tool? [LIST]")
    @Comment("blacklisted-blocks: Which blocks won't be dug by the tool? [LIST]")
    @Comment("whitelisted-drops: Which items will be dropped by the tool? [LIST]")
    @Comment("blacklisted-drops: Which items won't be dropped by the tool? [LIST]")
    @Comment("     Please follow the \"TYPE\" or \"TYPE:DATA\" format for drops and blocks.")
    @Comment("")
    public static String TOOLS = "tools";

}
